/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 

 */
package frames;
import java.awt.Image;
import static java.lang.Math.ceil;
import java.sql.*;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public final class AddStudents extends javax.swing.JFrame {

    /**
     * Creates new form AddStudents
     * @throws java.sql.SQLException
     */
    
  
    public AddStudents() throws SQLException {
        initComponents();
        Image icon=new ImageIcon(this.getClass().getResource("/dorm.jpeg")).getImage();
    this.setIconImage(icon);
        assign();
        table();
    }
    Connection conn;
    PreparedStatement stmt;
    public void assign(){
        try {
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitorymanagement","root","");
        } catch (SQLException ex) {
            Logger.getLogger(AddStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
           
        if(female.isSelected()){
        int room,floor,block;
        Statement sta=conn.createStatement();
             ResultSet rs=sta.executeQuery("SELECT ROW_NUMBER() OVER (ORDER BY batchyear, department, idnumber) AS `row_number`, femalestudents.* FROM femalestudents ORDER BY batchyear, department, idnumber;");
             int c;
             while(rs.next()){
                 c=rs.getInt("row_number")-1;
                 String i=rs.getString("idnumber");
                 
             room=(int)((c/4))%24+1;
             floor=(int)(c/96)%5;
             block=(int)(c/480)+1;
                 stmt=conn.prepareStatement("Update femalestudents set roomnumber=?,floornumber=?,blocknumber=? where idnumber=?");
                 stmt.setInt(1, room);
                 stmt.setInt(2, floor);
                 stmt.setInt(3, block);
                 stmt.setString(4, i);
                 stmt.executeUpdate();}
//             stmt=conn.prepareStatement("INSERT INTO students SELECT * FROM femalestudents ;");
             stmt.executeUpdate();
        }else{
        int room,floor,block;
        Statement sta=conn.createStatement();
             ResultSet rs=sta.executeQuery("SELECT ROW_NUMBER() OVER (ORDER BY batchyear, department, idnumber) AS `row_number`, malestudents.* FROM malestudents ORDER BY batchyear, department, idnumber;");
             int c;
             while(rs.next()){
                 c=rs.getInt("row_number")-1;
                 String i=rs.getString("idnumber");
              
             room=((int)(c/4)%24)+1;
             floor=(int)(c/96)%5;
             block=(int)(c/480)+8;
                 stmt=conn.prepareStatement("Update malestudents set roomnumber=?,floornumber=?,blocknumber=? where idnumber=?");
                 stmt.setInt(1, room);
                 stmt.setInt(2, floor);
                 stmt.setInt(3, block);
                 stmt.setString(4, i);
                 stmt.executeUpdate();
//             stmt=conn.prepareStatement("INSERT INTO students SELECT * FROM malestudents ;");
             stmt.executeUpdate();
             }
        
        }}catch(SQLException e){
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this,"Bad Connection");
//                    0988058226
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        container = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        theTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        department = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        gender.add(male);
        gender.add(female);

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setBackground(new java.awt.Color(153, 153, 255));
        container.setAutoscrolls(true);

        jLabel1.setText("ID Number :");

        jLabel2.setText("First Name :");

        jLabel3.setText("Last Name :");

        jLabel4.setText("Department :");

        jLabel5.setText("Batch Year :");

        jButton1.setText("Add Student");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        theTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDNumber", "First Name", "Last Name", "Department", "Year", "Gender", "Room", "Floor", "Block"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        theTable.setColumnSelectionAllowed(true);
        theTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                theTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(theTable);
        theTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton2.setText("Edit");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        female.setText("Female");

        male.setText("Male");

        jLabel6.setText("Gender:");

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016" }));
        year.setSelectedIndex(-1);
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Civil Engineering", "Electromechanical Engineering", "Chemical Engineering ", "Electrical Engineering", "Environmental Engineering", "Mechanical Engineering", "Architecture", "Biotechnology ", "Industrial Chemistry", "Geology", "Food Science", "Mining Engineering", " ", " " }));
        department.setSelectedIndex(-1);

        jButton4.setBackground(new java.awt.Color(102, 51, 255));
        jButton4.setFont(new java.awt.Font("Cambria", 3, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 153, 153));
        jButton4.setText("Complete Registration");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(female, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(male, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(containerLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6))
                            .addGroup(containerLayout.createSequentialGroup()
                                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(female)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(male)))
                        .addGap(17, 17, 17)
                        .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 255));
        jLabel7.setText("Register Students Here");

        update.setBackground(new java.awt.Color(204, 204, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(update)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Information");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu5.setText("From Another database");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
//    boolean flag;
    public void table() throws SQLException{
        int c;
         conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
         
             
        stmt=conn.prepareStatement(" SELECT * FROM femalestudents UNION SELECT * FROM malestudents  ORDER BY gender,roomnumber;");
        ResultSet rs=stmt.executeQuery();
        
        ResultSetMetaData rsmd=rs.getMetaData();
        
        c=rsmd.getColumnCount();
        DefaultTableModel df=(DefaultTableModel)theTable.getModel();
        df.setRowCount(0);
        while(rs.next()){
             Vector v=new Vector();
            for (int i=1;i<c;i++){          
            v.add(rs.getString("idnumber"));
            v.add(rs.getString("firstname"));
            v.add(rs.getString("lastname"));
            v.add(rs.getString("department"));
            v.add(rs.getString("batchyear"));
            v.add(rs.getString("Gender"));
            v.add(rs.getInt("roomnumber"));
            v.add(rs.getInt("floornumber"));
            v.add(rs.getInt("blocknumber"));
            
            }
            
            df.addRow(v);
        }
        
        id.setText("");
        fname.setText("");
        lname.setText("");
        gender.clearSelection();
        department.setSelectedIndex(-1);
        year.setSelectedIndex(-1);
        id.requestFocus();
        
    
    
    }
        
            
    
    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Admin ad=new Admin();
        ad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Admin h=new Admin();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel Df=(DefaultTableModel)theTable.getModel();
        int sidx=theTable.getSelectedRow();
        
        try{
            String idn=Df.getValueAt(sidx, 0).toString();
            String g=Df.getValueAt(sidx, 5).toString();
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
            
            
            if(g.equals("Female")){
                stmt=conn.prepareStatement("delete from femalestudents  where idnumber=?");
                stmt.setString(1, idn);
                stmt.executeUpdate();
                
            }else{
                stmt=conn.prepareStatement("delete from malestudents  where idnumber=?");
                stmt.setString(1, idn);
                stmt.executeUpdate();
            }
                JOptionPane.showMessageDialog(this, "Deleted Successfully");
                assign();
                table();
            id.setText("");
            fname.setText("");
            lname.setText("");
            gender.clearSelection();

            id.requestFocus();
        }
        catch(SQLException e){
            //            JOptionPane.showMessageDialog(this, "Connection Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        // TODO add your handling code here:
        DefaultTableModel Df=(DefaultTableModel)theTable.getModel();
        int sidx=theTable.getSelectedRow();
        try{
            String idn=Df.getValueAt(sidx, 0).toString();
            String ids=id.getText();
            String fn=fname.getText();
            String ln=lname.getText();
            String batchyear=(String)year.getSelectedItem();
            String dept=(String)department.getSelectedItem();
            String gen;
            if(female.isSelected()){
                gen=female.getText();
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
                stmt=conn.prepareStatement("update femalestudents set firstname=?,lastname=?,department=?,batchyear=?,gender=?,idnumber=?  where idnumber=?");
                stmt.setString(1, fn);
                stmt.setString(2, ln);
                stmt.setString(3, dept);
                stmt.setString(4, batchyear);
                stmt.setString(5, gen);
                stmt.setString(6, ids);
                stmt.setString(7, idn);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated Successfully");
                assign();
                table();
                id.setText("");
                fname.setText("");
                lname.setText("");
                gender.clearSelection();

                id.requestFocus();
            }else if (male.isSelected()){
                gen=male.getText();
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
                stmt=conn.prepareStatement("update malestudents set  firstname=?,lastname=?,department=?,batchyear=?,gender=? ,idnumber=? where idnumber=?");
                stmt.setString(1, fn);
                stmt.setString(2, ln);
                stmt.setString(3, dept);
                stmt.setString(4, batchyear);
                stmt.setString(5, gen);
                stmt.setString(6, ids);
                stmt.setString(7, idn);
                stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "Updated Successfully");
                assign();
                table();
                id.setText("");
                fname.setText("");
                lname.setText("");
                gender.clearSelection();

                id.requestFocus();
            }else{
                JOptionPane.showMessageDialog(this, "Empty Input Not Valid");
                id.setText("");
                fname.setText("");
                lname.setText("");
                gender.clearSelection();

                id.requestFocus();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Connection Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
//82100
//
    }//GEN-LAST:event_jButton2MouseClicked

    private void theTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_theTableMouseClicked
        DefaultTableModel Df=(DefaultTableModel)theTable.getModel();
        int sidx=theTable.getSelectedRow();
        id.setText(Df.getValueAt(sidx, 0).toString());
        fname.setText(Df.getValueAt(sidx, 1).toString());
        lname.setText(Df.getValueAt(sidx, 2).toString());
        department.setSelectedItem(Df.getValueAt(sidx, 3).toString());
        year.setSelectedItem(Df.getValueAt(sidx, 4).toString());
        if(Df.getValueAt(sidx, 5).toString().equals("Female"))
        gender.setSelected(female.getModel(), true);
        else{
           gender.setSelected(male.getModel(), true); 
        }

    }//GEN-LAST:event_theTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idnum=id.getText();
        String firstname=fname.getText();
        String lastname=lname.getText();
        String dept=(String)department.getSelectedItem();
        String m=male.getText();
        String f=female.getText();
        String batchyear=(String)year.getSelectedItem();
        if(idnum.equals("")||firstname.equals("")||lastname.equals("")||dept.equals("")||batchyear.equals("")||(male.isSelected()==false && female.isSelected()==false)){
            JOptionPane.showMessageDialog(this,"Empty Input Is Not Acceptable.");
        }
        else {if(male.isSelected()){
                try{

                    conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
                    stmt=conn.prepareStatement("Insert into malestudents (idnumber,firstname,lastname,department,batchyear,gender,roomnumber,floornumber,blocknumber) values(?,?,?,?,?,?,?,?,?) ");
                    stmt.setString(1, idnum);
                    stmt.setString(2, firstname);
                    stmt.setString(3, lastname);
                    stmt.setString(4, dept);
                    stmt.setString(5, batchyear);
                    stmt.setString(6,m);
                    int room=1;
                    int floor=0;
                    int block=8;
                    stmt.setInt(7,room);
                    stmt.setInt(8,floor);
                    stmt.setInt(9,block);
                    stmt.executeUpdate();
                    assign();
                    JOptionPane.showMessageDialog(this, "Record Added");
                    table();
                }catch(SQLException q){if (q.getSQLState().equals("45000")) {
                        JOptionPane.showMessageDialog(this, "ID Number Already Exists");}
                        else{
                             JOptionPane.showMessageDialog(this, "Bad Connection");
                        }
                }}else{
                    try{
                        conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/dormitoryManagement","root","");
                        stmt=conn.prepareStatement("Insert into femalestudents (idnumber,firstname,lastname,department,gender,batchyear,roomnumber,floornumber,blocknumber)values(?,?,?,?,?,?,?,?,?) ");
                        stmt.setString(1, idnum);
                        stmt.setString(2, firstname);
                        stmt.setString(3, lastname);
                        stmt.setString(4, dept);
                        stmt.setString(5, f);
                        stmt.setString(6,batchyear);
                        int room=1;
                        int floor=0;
                        int block=1;
                        stmt.setInt(7,room);
                        stmt.setInt(8,floor);
                        stmt.setInt(9,block);
                        stmt.executeUpdate();
                        assign();
                        JOptionPane.showMessageDialog(this, "Record Added");
                        table();
                    }catch(SQLException q){
                        if (q.getSQLState().equals("45000")) {
                        JOptionPane.showMessageDialog(this, "ID Number Already Exists");}
                        else{
                             JOptionPane.showMessageDialog(this, "Bad Connection");
                        }
//q.printStackTrace();

                    }
                    
             }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            // TODO add your handling code here:
            assign();
            table();
        } catch (SQLException ex) {
            Logger.getLogger(AddStudents.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        FromDatabaseTable f=new FromDatabaseTable();
        f.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenu5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AddStudents().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AddStudents.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JComboBox<String> department;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fname;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JRadioButton male;
    private javax.swing.JTable theTable;
    private javax.swing.JButton update;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables

}
