/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import java.awt.Image;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class FromDatabaseTable extends javax.swing.JFrame {

    /**
     * Creates new form FromDatabaseTable
     */
    public FromDatabaseTable() {
        initComponents();
        Image icon=new ImageIcon(this.getClass().getResource("/dorm.jpeg")).getImage();
    this.setIconImage(icon);
    }
    Connection conn;
    PreparedStatement stmt;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void assigned(String db,String t){
        try{
            String url="jdbc:mysql://localhost:3306/"+db;
        conn=DriverManager.getConnection(url,"root","");
        stmt=conn.prepareStatement("INSERT into dormitorymanagement.femalestudents (idnumber,firstname,lastname,department,gender,batchyear,roomnumber,floornumber,blocknumber) select idnumber,firstname,lastname,department,gender,batchyear,roomnumber,floornumber,blocknumber from "+t+" where gender=?");
    
        stmt.setString(1, "Female");
        int f=stmt.executeUpdate();
        stmt=conn.prepareStatement("INSERT into dormitorymanagement.malestudents (idnumber,firstname,lastname,department,gender,batchyear,roomnumber,floornumber,blocknumber) select idnumber,firstname,lastname,department,gender,batchyear,roomnumber,floornumber,blocknumber from "+t +" where gender=?");
        stmt.setString(1, "Male");        
        int m=stmt.executeUpdate();
        Statement state=conn.createStatement();
       
        }catch(SQLException e){
//            JOptionPane.showMessageDialog(this,"No such database or table exsits in your machine");
                e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TheContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tlable = new javax.swing.JLabel();
        dblable = new javax.swing.JLabel();
        dbname = new javax.swing.JTextField();
        tname = new javax.swing.JTextField();
        assign = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        home = new javax.swing.JMenu();
        addStudents = new javax.swing.JMenu();
        information = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        TheContainer.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel1.setText("You can add the database name and the table name to do the assignation");

        tlable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        tlable.setText("Table Name:");

        dblable.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        dblable.setText("Database Name:");

        dbname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        tname.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N

        assign.setBackground(new java.awt.Color(153, 153, 255));
        assign.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        assign.setText("Assign");
        assign.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TheContainerLayout = new javax.swing.GroupLayout(TheContainer);
        TheContainer.setLayout(TheContainerLayout);
        TheContainerLayout.setHorizontalGroup(
            TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TheContainerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TheContainerLayout.createSequentialGroup()
                        .addGroup(TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dblable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tlable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dbname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assign))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TheContainerLayout.setVerticalGroup(
            TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TheContainerLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dblable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dbname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TheContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(assign)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/out3.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TheContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(TheContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        home.setText("Home");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jMenuBar1.add(home);

        addStudents.setText("AddStudents");
        addStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addStudentsMouseClicked(evt);
            }
        });
        jMenuBar1.add(addStudents);

        information.setText("Information");
        information.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informationMouseClicked(evt);
            }
        });
        jMenuBar1.add(information);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignActionPerformed
        // TODO add your handling code here:
        if(dbname.getText().equals("")||tname.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Invalid Input");
        }else{
      try{
         
        assigned(dbname.getText(),tname.getText());
        AddStudents a=new AddStudents();
        a.assign();
        a.table();
        JOptionPane.showMessageDialog(this, "Assigned Successfully");
        
      }catch(SQLException e){
          JOptionPane.showMessageDialog(this, "Invalid Database or Table");
      }finally{
          dbname.setText("");
        tname.setText("");
        dbname.requestFocus();
      }}
        
    }//GEN-LAST:event_assignActionPerformed

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        Home h=new Home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_homeMouseClicked

    private void addStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentsMouseClicked
        try {
            // TODO add your handling code here:
            AddStudents a=new AddStudents();
            a.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(FromDatabaseTable.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addStudentsMouseClicked

    private void informationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informationMouseClicked
        // TODO add your handling code here:
        Admin a=new Admin();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_informationMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromDatabaseTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromDatabaseTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromDatabaseTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromDatabaseTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FromDatabaseTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TheContainer;
    private javax.swing.JMenu addStudents;
    private javax.swing.JButton assign;
    private javax.swing.JLabel dblable;
    private javax.swing.JTextField dbname;
    private javax.swing.JMenu home;
    private javax.swing.JMenu information;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tlable;
    private javax.swing.JTextField tname;
    // End of variables declaration//GEN-END:variables
}
